# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api



server:
  port: 8081
# 扫描 mapper.xml
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mappers/*.xml
    - classpath*:com/**/mapper/*.xml


# 日志配置
logging:
  level:
    com.chryl: debug
    org.springframework: warn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chryl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: chryl
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid